services:
  - type: web
    name: vetricoders-django
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    autoDeploy: true
    envVars:
      - key: DJANGO_SECRET_KEY
        value: "your-secret-key"
      - key: DATABASE_URL
        fromDatabase:
          name: vetricoders-db
      - key: DEBUG
        value: "False"
databases:
  - name: vetricoders-db
    databaseName: vetricoders
    user: vetricoders_user

staticDirs:
  - path: /media
    dir: media
